fix yaml

diff --git a/.github/workflows/azure-static-web-apps-yellow-ocean-05f710710.yml b/.github/workflows/azure-static-web-apps-yellow-ocean-05f710710.yml
--- a/.github/workflows/azure-static-web-apps-yellow-ocean-05f710710.yml
+++ b/.github/workflows/azure-static-web-apps-yellow-ocean-05f710710.yml
@@ -19,8 +19,7 @@ jobs:
       contents: read
     steps:
       # Checkout du code
-      - name: Checkout code
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3
         with:
           submodules: true
           lfs: false
@@ -40,6 +39,12 @@ jobs:
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
 
+      # Supprimer la ressource existante (si elle existe)
+      - name: Delete existing resource group (if exists)
+        run: |
+          az group show --name portfolio || echo "Resource group does not exist, nothing to delete"
+          az group delete --name portfolio --yes --no-wait || echo "Failed to delete resource group (maybe it doesn't exist)"
+        
       # Initialiser Terraform dans le répertoire tf/
       - name: Terraform Init
         run: terraform init -input=false
@@ -65,14 +70,14 @@ jobs:
         run: npm install @actions/core@1.6.0 @actions/http-client
 
       # Obtenir le token d'identité GitHub pour le déploiement
-      - name: Get GitHub ID Token
+      - name: Get Id Token
         uses: actions/github-script@v6
         id: idtoken
         with:
-          script: |
-            const core = require('@actions/core');
-            return await core.getIDToken();
-          result-encoding: string
+           script: |
+               const coredemo = require('@actions/core')
+               return await coredemo.getIDToken()
+           result-encoding: string
 
       # Déployer l'application sur Azure Static Web App
       - name: Build And Deploy
@@ -81,9 +86,9 @@ jobs:
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
           action: "upload"
-          app_location: "/"  # Chemin vers le code source de l'application React
-          api_location: ""   # Chemin vers l'API si tu en as une
-          output_location: "dist"  # Répertoire où la version construite de l'application se trouve
+          app_location: "/" # Chemin vers le code source de l'application React
+          api_location: "" # Chemin vers l'API si tu en as une
+          output_location: "dist" # Répertoire où la version construite de l'application se trouve
           github_id_token: ${{ steps.idtoken.outputs.result }}
 
   close_pull_request_job:
